-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "demiJApremDebutMin" INTEGER NOT NULL DEFAULT 720,
ADD COLUMN     "demiJMatinFinMin" INTEGER NOT NULL DEFAULT 810,
ADD COLUMN     "demiJSeuilMin" INTEGER NOT NULL DEFAULT 90;
